export const DEFAULT_EXERCISES = {
  "Core - Static": [
    "Kneeling Plank","Plank","Plank + leg raise","Plank + arm raise",
    "Plank - hands on high box","Plank - hands on box","Plank on ball",
    "Power Plank","Weighted Plank","Fitball Plank",
    "Side Plank","Kneeling Side Plank","Side Plank + leg raise",
    "Side Plank + DB","Side Plank with rotation",
    "Straight Arm Plank","Straight Arm Plank + arm raise",
    "Hollow Hold","Hollow Scissors","Hollow Hold or Hollow Scissors"
  ],
  "Core - Dynamic": [
    "Dead Bug","Dead Bug - no weight","Dead Bug + roller",
    "Scissors","Light Scissors",
    "T-Spine Rotation","Red Band",
    "Standing Pallof Anti-Rotation","Standing Pallof Anti-Rotation 20+ sec",
    "Pallof Press - cable","Pallof Press Anti-Rotation","Ab Roller"
  ],
  "Squat / Knee Dominant": [
    "Box Squat (sit to box)","Box Squat - high box","Box Squat + medicine ball",
    "TRX Squat","TRX Squat - assisted","Bodyweight Squat",
    "Goblet Squat","Goblet Squat (KB)","Goblet Squat KB",
    "Landmine Front Squat","Landmine Sumo Squat",
    "Front Squat with medicine ball","Front Squat + medicine ball",
    "Single KB Front Squat (rack)","Double KB Front Squat (rack)",
    "Barbell Front Squat","Barbell Back Squat",
    "Belt Squat","Zercher Squat","Hack Squat",
    "Split Squat","Bulgarian Split Squat BW",
    "Bulgarian Split Squat + DB","Bulgarian Split Squat + 2 KB",
    "Bulgarian Goblet Squat",
    "Sissy Squat","Barcelona Squat",
    "Wall Sit","Wall Sit + plate",
    "Isometric Squat with band",
    "One and a half Squat - KB/DB",
    "Jefferson Squat","Hatfield Squat","Hockey Squat"
  ],
  "Lunge / Step": [
    "Reverse Lunge with assist (cage)","Reverse Lunge - BW","Reverse Lunge + DB",
    "Reverse Lunge + medicine ball/plate",
    "Reverse Lunge from elevation",
    "Reverse Lunge from elevation + DB",
    "Forward Lunge","Forward Lunge + DB",
    "Walking Lunge","Walking Lunge + DB",
    "Walking Lunge + barbell (back squat position)",
    "Walking Lunge + barbell (front squat position)",
    "Lunge Complex",
    "Hockey Lunge + medicine ball/plate",
    "Hockey Lunge walking + medicine ball/plate",
    "Step-up on low box","Step-up on box",
    "Step-up + medicine ball/plate/DB",
    "Step-up + barbell"
  ],
  "Push - Vertical": [
    "Single Arm DB Press - seated","Single Arm KB Press - seated",
    "Single Arm KB Press - kneeling","Single Arm DB Press - half kneeling",
    "Single Arm DB Press - standing","Single Arm DB Press - single leg",
    "DB Overhead Press - seated","DB Overhead Press - standing",
    "DB Overhead Press - alternating",
    "Barbell Overhead Press - seated","Barbell Overhead Press - standing",
    "Barbell Push Press","Barbell Push Jerk",
    "Landmine Press one arm","Landmine Press one arm - kneeling",
    "Landmine Press one arm - standing",
    "H.K Landmine Press - one arm","T.K Landmine Press one arm",
    "Single Arm KB/DB Press + band"
  ],
  "Push - Horizontal": [
    "Wall Push-up","Push-up on high box","Push-up on medium box",
    "Kneeling Push-up (legs extended)","Kneeling Push-up (legs bent)",
    "TRX Push-up","Push-up with medicine ball under belly",
    "Push-up with foam roller hold","Push-ups",
    "Push-ups feet elevated","Banded Push-ups","Push-up + plate on back",
    "Ring/TRX Push-up feet elevated","Fitball Push-up",
    "Parallel Bar Push-up (dips)","Single Arm Push-up on high box",
    "Single Arm Push-up on low box","Single Arm Push-up with medicine ball",
    "Single Arm Push-up",
    "90° Push-up on box","90° Push-up hold on box",
    "Wall Walk + Push-up","Handstand Push-up",
    "Push-ups + DB Close Grip Bench Press",
    "Floor Press - single DB","Floor Press - two DB","Floor Press - barbell",
    "DB Bench Press - two DB","DB Bench Press ALT arm",
    "Barbell Bench Press","DB Flyes on bench",
    "Parallel Bar Dips","Single Arm DB Floor Press"
  ],
  "Pull - Vertical": [
    "Lat Pulldown - front","Lat Pulldown - behind head",
    "H.K Lat Pulldown - one arm",
    "Cable Pull - standing single arm",
    "Box Assisted Pull-up","Jump Pull-up",
    "Band Assisted Pull-up","Partner Assisted Pull-up",
    "Chin-ups (supinated)","Pull-ups",
    "Weighted Pull-ups (band/vest/DB)"
  ],
  "Pull - Horizontal": [
    "Maxwell Pull standing","TRX/Ring Row 45°",
    "TRX/Ring Row horizontal (90°)",
    "TRX/Ring Row legs on floor","TRX/Ring Row legs elevated",
    "Isometric Row with band","Isometric Row on wood device",
    "Single Arm DB Row - standing bent over",
    "Two Arm DB Row - standing bent over",
    "Two Arm DB Row - alternating",
    "Single Arm DB Row on bench (knee supported)",
    "Single Arm DB Row on bench (legs extended)",
    "Single/Two Arm DB Row - chest on incline bench",
    "Single Arm Landmine Row","Two Arm Landmine Row",
    "DB/KB Row on GHD",
    "Cable Row - standing single arm",
    "Barbell Bent Over Row (strict)","Barbell Bent Over Row (athletic)",
    "Australian Bench Row (bench on steppers)",
    "TRX Row","Single Arm DB Row","Single Arm DB Row on bench",
    "Two Arm DB Row - bent over","Two Arm DB Row - incline bench",
    "DB Row on bench","Pulley Row","Band Pull Apart"
  ],
  "Hip Hinge / Deadlift": [
    "Hip Hinge Learning (stick, wall, mobility)",
    "KB Deadlift - held at chest","KB Deadlift from elevation",
    "KB Deadlift from elevation (yoga block)","KB Deadlift from floor",
    "Sumo Deadlift - two KB (between legs)",
    "Suitcase Deadlift - one arm","Suitcase Deadlift - two arms",
    "Single Arm Landmine Deadlift",
    "Trap Bar Deadlift from elevation","Trap Bar Deadlift from floor",
    "Barbell Deadlift from elevation (steppers)",
    "Barbell Deadlift from knee height",
    "Conventional Deadlift","Sumo Deadlift",
    "Maxwell Deadlift","Bulgarian Deadlift","Keystone Deadlift",
    "One and half stance Deadlift",
    "DB Romanian Deadlift","Barbell Romanian Deadlift",
    "Stiff Leg Deadlift (knees locked)",
    "Conventional Deadlift + band/fat grips/chains",
    "Isometric Deadlift on wood device",
    "Single Arm Single Leg DL learning (rings/roller)",
    "Single Arm Single Leg DL - landmine",
    "Single Arm Single Leg DB Deadlift",
    "Single Leg Barbell Deadlift",
    "Single Arm KB Deadlift",
    "Hip Lift from floor","Hip Lift - one leg on ball",
    "Single Leg Hip Lift","Single Leg Hip Lift on ball",
    "Single Leg Hip Lift + weight","Single Leg Hip Lift - assisted"
  ],
  "Rotation / Anti-Rotation": [
    "Woodchop kneeling - DB/cable (high to low)",
    "Woodchop kneeling - DB/cable (low to high)",
    "Woodchop half-kneeling - DB/cable (high to low)",
    "Woodchop half-kneeling - DB/cable (low to high)",
    "Woodchop half-kneeling - raised foot",
    "Woodchop standing - DB/cable",
    "Woodchop standing dynamic - DB/cable",
    "Woodchop unilateral - DB/cable",
    "Pallof Press - kneeling","Pallof Press - half kneeling",
    "Pallof Press - standing","Pallof Press - single leg",
    "Standing Pallof Anti-Rotation","Standing Pallof Anti-Rotation 20+ sec",
    "Pallof Press - cable","Pallof Press Anti-Rotation",
    "Quadruped with/without stick",
    "3D Strap rotation","Windmill variations"
  ],
  "Accessory / Isolation": [
    "Face Pull","Face Pull - band","Face Pull - cable",
    "Rear Delt Raise - DB","Rear Delt Raise - bench",
    "Rear Delt Raise - bent over","Rear Delt Raise - DB seated",
    "Rear Delt - band","Single Arm DB Lateral Raise",
    "DB Biceps Curl","DB Biceps/Triceps","Biceps/Triceps",
    "Farmer Walk","Bench Stretch","Bench Stretch - roller",
    "Stretching - mobility","Hip mobility stretching",
    "Ab Roller"
  ]
};

export const SESSIONS = [
  { key: "t1", label: "VERTIKALNA RAVAN", color: "#4472C4", light: "#D6E4F0" },
  { key: "t2", label: "HORIZONTALNA RAVAN", color: "#70AD47", light: "#E2EFDA" },
  { key: "t3", label: "UNILATERALNA", color: "#ED7D31", light: "#FCE4D6" }
];
